import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:p2_todo/model/task.dart';

CollectionReference<Task> getTaskCollection(){
   return  FirebaseFirestore.instance.collection('task').withConverter<Task>
    (fromFirestore: ((snapshot, options) => Task.fromjosn(snapshot.data()!)), toFirestore: (task, options) =>task.tojson() );
}
Future<void> addTaskToFireStore(Task task){
// CollectionReference<Map<String,dynamic>> 
  var collection =  getTaskCollection();
  var docRef = collection.doc();
  task.id = docRef.id; // assign autogenerated id to task
  return docRef.set(task);
}
Future<void> deleteTaskFromFireStore(Task task){
 return getTaskCollection().doc(task.id).delete();
}